default:
  http_metas:
    content-type: text/html

  metas:
    title:        Doctrine - Open Source PHP 5 ORM
    robots:       index, follow
    description:  Doctrine is a Open Source OO PHP 5 ORM
    keywords:     doctrine, php, database, orm
    language:     en

  stylesheets:    [main, layout]

  javascripts:    []

  has_layout:     on
  layout:         layout
