generator:
  class:              sfDoctrineAdminGenerator
  param:
    model_class:      BlogPost
    theme:            default
    edit:
      display:        [name, body]
      fields:
        body:
          type:       textarea_tag
          params:     size=60x15